name: Build and release dylib

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          make FINALPACKAGE=1
          # Find the dylib even if the path changes slightly
          echo "DYLIB_PATH=$(find .theos/obj -name "*.dylib" | head -n 1)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.DYLIB_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
